### ISSUE TITLE
[Item Report] Nord

### ISSUE THREAD

**Issue by zaldih** [mue/marketplace#15]
**Description**

Since a few days my background image does not load, as shown in the picture.

**Item version**

1.2.1

**Screenshots**

![image](https://github.com/mue/marketplace/assets/16844185/47d59d00-0fcc-4392-b287-094139efc9e6)

**Additional context**

Looking at the content of the extension, the image address points to a Discord cdn address, which appears to have been removed.

**Comment by davidcralph** [comment]
Should work after marketplace content gets updated (cc @eartharoid), then you will need to reinstall the item in the extension.

Thanks for the issue report!

**Comment by eartharoid** [comment]
Marketplace should be updated now.

**Comment by zaldih** [comment]
wow that was fast. Thanks guys!

I think it hasn't updated yet (maybe ci problems?) Anyway I'll try again tomorrow.
