### ISSUE TITLE
Error 500 on https://marketplace.muetab.com/all

### ISSUE THREAD

**Issue by austinhuang0131** [mue/marketplace#5]
and obviously it can't load on the extension/demo either

![image](https://user-images.githubusercontent.com/16656689/112178002-d0a69000-8bcf-11eb-87c5-cf3d3a4c4ff7.png)

**Comment by davidcralph** [comment]
Thank you for reminding me 😅 Need to get round to fixing and overhauling the marketplace system but been focused on the settings part of 5.0 Mue currently.

I don't believe I have your contact details on Discord but I wanted to quickly warn you that all development of mue/mue has shifted to the 5.0-dev branch.

![image](https://user-images.githubusercontent.com/14052956/112179966-0a3cc280-8bf3-11eb-9d20-3af057947f94.png)

I'll get round to switching default repository and putting a warning message on the README in a minute or two.

**Comment by austinhuang0131** [comment]
doing translations, not deving

do you seriously not remember my name

**Comment by davidcralph** [comment]
It's back 🎉
